package com.suman.memoryarchitect.domain.generation

import com.suman.memoryarchitect.domain.model.DifficultyTier
import com.suman.memoryarchitect.domain.model.GameMode
import com.suman.memoryarchitect.domain.model.LevelSpec
import java.time.LocalDate
import java.time.ZoneOffset
import java.time.temporal.WeekFields
import java.util.Locale

/**
 * Fully on-device Daily/Weekly Challenge generation - the Firebase-Spark-compatible replacement
 * for what used to be a Cloud-Function-backed shared Firestore document (`dailyChallenge/current`/
 * `weeklyChallenge/current`, generated by `functions/src/index.ts`'s `getDailyChallenge`/
 * `getWeeklyChallenge`). Deterministic purely from the calendar date/ISO week - every player's
 * device independently computes the identical seed for "today"/"this week" and feeds it through
 * the exact same [LevelGenerator] Classic/Practice already use, so everyone lands on the same
 * puzzle with zero network round-trip and no shared document for a malicious client to poison.
 * Shared by [com.suman.memoryarchitect.data.repository.LevelRepositoryImpl] (the actual played
 * level) and [com.suman.memoryarchitect.data.repository.ChallengeRepositoryImpl] (Home's
 * lightweight preview cards) so both always agree on today's/this week's puzzle.
 */
object PeriodicChallengeGenerator {
    private val difficultyEngine = DifficultyEngine()
    private val levelGenerator = LevelGenerator()

    // Fixed tiers, not caller-supplied - a deliberately small, non-tunable puzzle size per
    // DifficultyEngine.computeConstraints' own pinned Daily/Weekly branch, one notch harder for
    // Weekly (HARD vs MEDIUM) so it's genuinely tougher via more objects/rotation, not a shorter
    // timer. Matches this pair's previous Cloud-Function-generated behavior.
    fun generateDailyChallenge(): LevelSpec = generate(GameMode.DAILY_CHALLENGE, DifficultyTier.MEDIUM, "daily", dailyPeriodKey())

    fun generateWeeklyChallenge(): LevelSpec = generate(GameMode.WEEKLY_CHALLENGE, DifficultyTier.HARD, "weekly", weeklyPeriodKey())

    private fun generate(mode: GameMode, tier: DifficultyTier, prefix: String, periodKey: String): LevelSpec {
        val seed = "$prefix-$periodKey".hashCode().toLong()
        val constraints = difficultyEngine.computeConstraints(tier, streak = 0, mode = mode)
        return levelGenerator.generate(seed = seed, mode = mode, difficultyTier = tier, constraints = constraints)
    }

    /** UTC calendar date, e.g. "2026-07-30" - mirrors
     * [com.suman.memoryarchitect.data.repository.LeaderboardRepositoryImpl]'s own `dailyPeriodKey()`,
     * so "today's leaderboard" and "today's puzzle" always agree on what day it is. */
    fun dailyPeriodKey(): String = LocalDate.now(ZoneOffset.UTC).toString()

    /** ISO year + ISO week number, e.g. "2026-W31" - mirrors
     * [com.suman.memoryarchitect.data.repository.LeaderboardRepositoryImpl]'s own `weeklyPeriodKey()`. */
    fun weeklyPeriodKey(): String {
        val today = LocalDate.now(ZoneOffset.UTC)
        val fields = WeekFields.ISO
        val week = today.get(fields.weekOfWeekBasedYear())
        val year = today.get(fields.weekBasedYear())
        return String.format(Locale.ROOT, "%04d-W%02d", year, week)
    }

    /** The UTC-midnight instant the current daily period key expires at, as epoch seconds. */
    fun dailyExpiresAtEpochSecond(): Long =
        LocalDate.now(ZoneOffset.UTC).plusDays(1).atStartOfDay(ZoneOffset.UTC).toEpochSecond()

    /** The next UTC Monday midnight the current weekly period key expires at, as epoch seconds. */
    fun weeklyExpiresAtEpochSecond(): Long {
        val today = LocalDate.now(ZoneOffset.UTC)
        val daysUntilNextMonday = 8 - today.dayOfWeek.value // dayOfWeek.value: Mon=1..Sun=7
        return today.plusDays(daysUntilNextMonday.toLong()).atStartOfDay(ZoneOffset.UTC).toEpochSecond()
    }
}
