/**
 * Mirrors domain/progression/ShopCatalog.kt's prices exactly - keep both in sync, the same
 * "mirrors X" convention mock-backend/progression.js already uses for the Kotlin progression
 * rules. Used only for server-side price validation (validatePurchaseReceipt below) - the full
 * catalog (names/rarity/rendering) lives client-side only, same as every other reward/achievement
 * catalog in this app.
 */
export const SHOP_CATALOG_PRICES: Record<string, number> = {
  FRAME_WOVEN_CORD: 180, FRAME_SILVER_LAUREL: 500, FRAME_MOLTEN_BRONZE: 1100, FRAME_CELESTIAL_HALO: 2800,
  // Premium Borders (flagship category) - 12 items, 3 per rarity. Mirrors ShopCatalog.kt exactly.
  BORDER_CLASSIC_SILVER: 170, BORDER_PEARL_WHITE: 210, BORDER_OBSIDIAN: 260,
  BORDER_PLATINUM: 450, BORDER_EMERALD: 550, BORDER_SAPPHIRE: 650,
  BORDER_RUBY: 1000, BORDER_CYBER_NEON: 1200, BORDER_LAVA: 1400,
  BORDER_ROYAL_GOLD: 2400, BORDER_DIAMOND_GLOW: 2900, BORDER_GALAXY: 3400,
  NAME_COLOR_SLATE: 150, NAME_COLOR_OCEAN_FADE: 420, NAME_COLOR_SUNSET_GRADIENT: 950, NAME_COLOR_PRISM_SHIFT: 2400,
  TIMER_CLASSIC_DOT: 200, TIMER_PULSE_RING: 480, TIMER_EMBER_SWEEP: 1050, TIMER_STARLIGHT_ARC: 2900,
  VICTORY_CONFETTI_POP: 220, VICTORY_GOLDEN_SPARKS: 550, VICTORY_FIREWORK_BURST: 1200, VICTORY_SUPERNOVA: 3200,
  CONFETTI_PAPER_TOSS: 170, CONFETTI_RIBBON_FALL: 430, CONFETTI_STAR_SHOWER: 980, CONFETTI_RAINBOW_CASCADE: 2500,
  STICKERS_DOODLE_PACK: 190, STICKERS_ADVENTURE_PACK: 470, STICKERS_COSMIC_PACK: 1150, STICKERS_MYTHIC_PACK: 3000,
  TROPHY_BRONZE_CUP: 210, TROPHY_SILVER_COMPASS: 520, TROPHY_GOLDEN_HOURGLASS: 1300, TROPHY_DIAMOND_CROWN: 3500,
  BACKGROUND_MISTY_DAWN: 190, BACKGROUND_TWILIGHT_HAZE: 480, BACKGROUND_AURORA_DRIFT: 1050, BACKGROUND_STARFIELD_DEEP: 2900,
  BADGE_BRONZE_LAUREL: 200, BADGE_SILVER_SEAL: 500, BADGE_GOLDEN_CREST: 1100, BADGE_ARCHITECT_SIGIL: 2800,
};

export const SPIN_COST_COINS = 150;
